# Generated by Django 6.0.4 on 2026-05-04 03:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อสนาม')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด / ขนาดสนาม')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ราคาต่อชั่วโมง (บาท)')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='วันที่')),
                ('record_type', models.CharField(choices=[('income', 'รายรับ'), ('expense', 'รายจ่าย')], default='income', max_length=10, verbose_name='ประเภทรายการ')),
                ('category', models.CharField(help_text='เช่น ค่าจองสนาม, ค่าบำรุงรักษา, ค่าไฟฟ้า', max_length=100, verbose_name='หมวดหมู่')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดรายการ')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='จำนวนเงิน (บาท)')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='ชื่อลูกค้า/ผู้จอง')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='เบอร์โทรศัพท์')),
                ('booking_date', models.DateField(verbose_name='วันที่จอง')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่มต้น')),
                ('end_time', models.TimeField(verbose_name='เวลาสิ้นสุด')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ยอดเงินรวม (บาท)')),
                ('payment_status', models.CharField(choices=[('pending', 'รอชำระเงิน'), ('paid', 'ชำระเงินแล้ว'), ('cancelled', 'ยกเลิก')], default='pending', max_length=20, verbose_name='สถานะการชำระเงิน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='stadium.field', verbose_name='สนาม')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='ชื่องานแข่งขัน/แมตช์')),
                ('team_a', models.CharField(max_length=100, verbose_name='ทีม A')),
                ('team_b', models.CharField(max_length=100, verbose_name='ทีม B')),
                ('match_date', models.DateField(verbose_name='วันที่แข่งขัน')),
                ('start_time', models.TimeField(verbose_name='เวลาแข่งขัน')),
                ('end_time', models.TimeField(verbose_name='เวลาสิ้นสุดการแข่ง')),
                ('score_a', models.IntegerField(default=0, verbose_name='คะแนนทีม A')),
                ('score_b', models.IntegerField(default=0, verbose_name='คะแนนทีม B')),
                ('status', models.CharField(choices=[('scheduled', 'รอแข่งขัน'), ('live', 'กำลังแข่งขัน'), ('completed', 'แข่งขันเสร็จสิ้น'), ('cancelled', 'ยกเลิกการแข่ง')], default='scheduled', max_length=20, verbose_name='สถานะการแข่ง')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='stadium.field', verbose_name='สนาม')),
            ],
        ),
    ]
