# Generated by Django 6.0.4 on 2026-05-04 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='ชื่อรายการแข่งขัน')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดรายการแข่ง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='stadium.tournament', verbose_name='รายการแข่งขัน'),
        ),
        migrations.CreateModel(
            name='TournamentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='เช่น สาย A, สาย B', max_length=100, verbose_name='ชื่อสาย / กลุ่มการแข่ง')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='stadium.tournament', verbose_name='รายการแข่งขัน')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='stadium.tournamentgroup', verbose_name='สายการแข่ง'),
        ),
    ]
