# Generated by Django 6.0.4 on 2026-05-04 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0002_tournament_match_tournament_tournamentgroup_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อทีม')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='team_logos/', verbose_name='โลโก้ทีม / รูปทีม')),
                ('main_players', models.TextField(blank=True, help_text='ใส่ชื่อสมาชิกคั่นด้วยจุลภาค', verbose_name='รายชื่อผู้เล่นตัวจริง')),
                ('sub_players', models.TextField(blank=True, help_text='ใส่ชื่อตัวสำรองคั่นด้วยจุลภาค', verbose_name='รายชื่อผู้เล่นตัวสำรอง')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียดอื่นๆ')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='stadium.tournament', verbose_name='รายการแข่งขัน')),
            ],
        ),
    ]
