# Generated by Django 6.0.4 on 2026-05-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0003_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='players_data',
            field=models.TextField(blank=True, default='[]', verbose_name='ข้อมูลผู้เล่นทั้งหมด (JSON)'),
        ),
    ]
