# Generated by Django 6.0.4 on 2026-05-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0004_team_players_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่เริ่มแข่งขัน'),
        ),
    ]
