# Generated by Django 6.0.4 on 2026-05-04 06:52

import stadium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0007_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=stadium.models.user_directory_path, verbose_name='รูปโปรไฟล์'),
        ),
    ]
