# Generated by Django 6.0.4 on 2026-05-04 07:06

import stadium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0008_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=stadium.models.team_directory_path, verbose_name='โลโก้ทีม / รูปทีม'),
        ),
    ]
