# Generated by Django 6.0.4 on 2026-05-04 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0009_alter_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='red_cards_a',
            field=models.IntegerField(default=0, verbose_name='ใบแดงทีม A'),
        ),
        migrations.AddField(
            model_name='match',
            name='red_cards_b',
            field=models.IntegerField(default=0, verbose_name='ใบแดงทีม B'),
        ),
        migrations.AddField(
            model_name='match',
            name='yellow_cards_a',
            field=models.IntegerField(default=0, verbose_name='ใบเหลืองทีม A'),
        ),
        migrations.AddField(
            model_name='match',
            name='yellow_cards_b',
            field=models.IntegerField(default=0, verbose_name='ใบเหลืองทีม B'),
        ),
    ]
