# Generated by Django 6.0.4 on 2026-05-04 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stadium', '0010_match_red_cards_a_match_red_cards_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='stadium.tournamentgroup', verbose_name='สายการแข่ง'),
        ),
    ]
